version: "3.9"


services:
  mysql:
    image: mysql:8.0.3
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
 
  mongodb:
    image: mongo:6.0.3
    ports:
      - "27018:27017"


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - mysql
      - mongodb
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql


  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
