version: "3.9"

services:
  mysql:
    image: mysql:8.0.3
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
  
  mongodb:
    image: mongo:6.0.3
    ports:
      - "27018:27017"