name: Java CI with Maven

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: Start Docker
      run: docker-compose -f "docker-compose.yml" up -d --build
      
    - name: Build with Maven
      run: mvn -B package
      
    - name: Run SonarQube Analysis
      run: mvn sonar:sonar
      
    - name: Run JaCoCo for Code Coverage
      run: mvn test jacoco:report
      
    - name: Stop Docker
      if: always()
      run: docker-compose down
